# Gitter
# Created by Linebeck
# © 2016 - 2023. All Rights Reserved.

SSH-Keys:
  SSH-Key-One:
    Name:
    SSH-Key-Path:
    SSH-Key-Password:


Sessions:
  Session-One:
    Name:
    Repository:
    Directory-Location:
    Repository-Type:
    SSH-Key-Name: